site_name: Knowledge Base
theme:
  name: material
  palette:
    primary: black
    accent: red
  features:
    - navigation.instant
#navigation
nav:
  - 'index.md'
  - 'linux.md'
  - Networking:
    - 'hub-switch-router.md'
    - 'network-models.md'
    - 'cables-and-interfaces.md'
    - 'ipv6.md'
  - 'docker.md'
  - 'moodle.md'
extra_css:
  - '_custom/custom.css'
markdown_extensions:
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
