site_name: Knowledge Base
theme:
  name: material
  palette:
    primary: black
    accent: red
  features:
    - navigation.instant
#navigation
nav:
  - 'index.md'
  - 'linux.md'
  - 'networking.md'
  - 'docker.md'
  - 'moodle.md'
extra_css:
  - '_custom/custom.css'
